# Generated by Django 2.1.3 on 2019-10-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
